### ISSUE TITLE
Menu Styling?

### ISSUE THREAD

**Issue by johnweland** [Cirex/atom-metro-ui#10]
How do I get the menu to the left side proceeding the opened files tree?

**Comment by Cirex** [comment]
You need to install [tool-bar](https://atom.io/packages/tool-bar) and [flex-tool-bar](https://atom.io/packages/flex-tool-bar) for that.

flex-tool-bar example can be found here:
https://github.com/Cirex/atom-metro-ui/blob/master/resources/toolbar.json

Available icons for MDL 1.0/2.0 can be found here:
https://github.com/Cirex/atom-metro-ui/blob/master/styles/icons/utf-codes/mdl.less
https://github.com/Cirex/atom-metro-ui/blob/master/styles/icons/utf-codes/metro.less
