### ISSUE TITLE
Top root folder not themed

### ISSUE THREAD

**Issue by juanvisbal** [Cirex/atom-metro-ui#11]
The top root folder in the Projects Pane is not being colored.
![screenshot 1](https://cloud.githubusercontent.com/assets/955241/9100386/f0bd7f60-3b9f-11e5-8009-f5db6543f52b.png)

**Comment by Cirex** [comment]
How were your tree-view items added so I can try and reproduce to look at the HTML?

**Comment by juanvisbal** [comment]
File -> Open Folder...

**Comment by Cirex** [comment]
Very odd to me. I personally don't use Atom for anything but i've never seen this happen using any normal forms of adding files to the tree-view while developing this theme.

I see the mention of **linter-flow** in the console and also the use of **php**. Are you using Facebook's Nuclide or any other package which in some way extends the default tree-view package?

**Comment by Cirex** [comment]
If you can open Atom in development mode and and copy the HTML for tree-view into a gist I can probably fix it. I would still like to figure out why your HTML somehow differs from mine though.
