### ISSUE TITLE
Use the `atom-workspace` tag instead of the `workspace` class.

### ISSUE THREAD

**Issue by jerone** [Cirex/atom-metro-ui#3]
In index.less: 

Use the `atom-workspace` tag instead of the `workspace` class.
Use the `atom-text-editor` tag instead of the `editor` class.
Use the selector `atom-text-editor[mini]` to select mini-editors.
Use the `atom-pane-container` tag instead of the `panes` class.
Use the `atom-pane` tag instead of the `pane` class.
Use the selector `atom-pane-axis.horizontal` instead of the `pane-row` class.
Use the selector `atom-pane-axis.vertical` instead of the `pane-column` class.
Use the selector `atom-panel.modal` instead of the `overlay` class.
Use the selector `atom-panel.left` instead of the `panel-left` class.
Use the selector `atom-panel.bottom` instead of the `panel-bottom` class.
Use the selector `atom-panel` instead of the `tool-panel` class.
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension. If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

Part of the [Atom 1.0 API deprecations](http://blog.atom.io/2015/05/01/removing-deprecated-apis.html).

**Comment by Cirex** [comment]
I have a newer version locally that i've been working on the past couple of days that fixes most of the deprecations. Once I get it in a state i'm happy with i'll get everything committed.

I've started over from scratch as i'm targeting Atom 1.x and Windows 10 so it might take me a week or two, but change is coming, and hopefully for the best.

**Comment by Cirex** [comment]
Fixed in master
