### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by lainsce** [Cirex/atom-metro-ui#7]
Could you make a dark variant of the theme just like in Windows 10 built in?

**Comment by Cirex** [comment]
It's already on my list of things to do when I have the time. There will be 4 themes in total:

Light
Dark
Adaptive Light
Adaptive Dark

**Comment by lainsce** [comment]
Oh, that's nice. OK, I'll wait!

**Comment by lainsce** [comment]
{Dark Theme Attempt](https://gist.github.com/lainsce/9de817f927052483268d)

Here's my attempt at it :D

**Comment by Cirex** [comment]
Goo start. I think I need to add an option to desaturate the the top bar so it's not as overpowering on dark themes

**Comment by lainsce** [comment]
Actually, on Windows 10 apps when you select the dark variant, the accent stays the same saturation.
It's only on the Light variant that the saturation fades by 20%

**Comment by Cirex** [comment]
That's why it would be a optional setting. Something you can toggle on/off if it's your preference

**Comment by lainsce** [comment]
Maybe a checkbox on the side of the accent box for adaptive saturation?
